site_name: CUDA programming
site_url: https://github.com/WonyoungCho/CUDA
site_description: Tutorial review of CUDA
repo_url: https://github.com/WonyoungCho/CUDA/
site_author: Wonyoung Cho

extra_javascript: [docs.js]

pages:
    - Home: 'index.md'
    - CUDA: 
        - 'Installation': 'CUDA.md'
        - 'Introduction': 'CUDA_int.md'
        - 'Example': 'CUDA_ex.md'
    - PyCUDA: 
        - 'Installation': 'PyCUDA.md'
        - 'Introduction': 'PyCUDA_int.md'
        - 'Example': 'PyCUDA_ex.md'
    - CuPy:
        - 'Installation': 'CuPy.md'
        - 'Introduction': 'Cupy_int.md'
    - GPU:
        - 'GTX TITAN X': 'gtxTitanX.md'
        - 'RTX 2080 Ti': 'rtx2080Ti.md'
    
theme: readthedocs
